server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/user/**

        - id: product-service
          uri: http://product-service:8082
          predicates:
            - Path=/products/**

        - id: cart-service
          uri: http://cart-service:8083
          predicates:
            - Path=/cart/**

        - id: order-service
          uri: http://order-service:8084
          predicates:
            - Path=/orders/**
