server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://user-db:5432/userdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

firebase:
  config-path: classpath:firebase-service-account.json
